apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pilotedge-audio-fetcher
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/leithatia/pilotedge-audio-fetcher
    targetRevision: main
    path: helm/pilotedge-audio-fetcher

  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

